version: 2
jobs:
  build:
    working_directory: /sls-py-req
    docker:
      - image: ubuntu:rolling
    steps:
      - checkout
      # Apt deps
      - run: apt -y update && apt -y install python3-pip python3.6 curl unzip
      # install nodejs
      - run: curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt -y install nodejs
      # install serverless
      - run: npm install -g serverless
      # install deps
      - run: npm i
      # lint:
      - run: npm run lint
      # test!
      - run: npm run test
      # create a user
      - run: useradd -m tester
      # give this dir to the test user
      - run: chown -R tester .
      # test as user!
      - run: su -c "npm run test" tester
